title: Simon Lizotte
email: simon.lizotte.1@ulaval.ca
#description: >- # this means to ignore newlines until "baseurl:"
  #Personal website of Simon Lizotte's papers, code and various small blog posts.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://simonlizotte.ca" # the base hostname & protocol for your site, e.g. http://example.com
social:
  github: siliz4
  twitter: slizotte_
  scholar: "https://scholar.google.ca/citations?user=P6OnTrwAAAAJ&hl=en"
  orcid: 0000-0002-5446-675X

# Build settings
theme: minima
plugins:
  - jekyll-feed

header_pages:
  - publications.md
  - code.md
  - posts.md

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
